<?php
$page = [
    'home' => 'view/home.php',
    'about' => 'view/about.php',
    'register' =>'view/register.php',
    'records' => "view/records.php",
    'error' => "view/error.php",
    'edit' => "view/edit.php",
    'form' => "view/form.php",
    'signup' => "view/signup.php",
    'index' => "view/index.php",
    'login' => "view/login.php",
    'contact' => "view/contact.php",
    'querypage' => "view/querypage.php",
    'loginadmin' => "view/loginadmin.php",
    'adminhome' => "view/adminhome.php",
    'adminrequests' => "view/adminrequests.php",
    'adminmessages' => "view/adminmessages.php",
    'logout' => "view/logout.php",
    'inbox' => "view/inbox.php",
    'userinbox' => "view/userinbox.php",
    'queryreplies' => "view/queryreplies.php",
    'status' => "view/status.php",
];